- name: Remove existing NodeSource repo
  ansible.builtin.shell: rm -f /etc/yum.repos.d/nodesource-*.repo

- name: Add NodeSource repo (Node 20)
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

- name: Install Node.js
  ansible.builtin.shell: yum install -y nodejs
  args:
    creates: /usr/bin/node 